engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
  pep8:
    enabled: true
  radon:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - "**.py"
  - "share/js/*.js"
  - "share/sass/*.scss"

exclude_paths:
  - ez_setup.py
  - versioneer.py
  - gwsumm/_version.py
  - docs/*
  - gwsumm/tests/*
