language: python

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - sourceline: deb http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
      - sourceline: deb-src http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
    packages:
      - pkg-config  # lal
      - zlib1g-dev  # lal
      - libgsl0-dev  # lal
      - swig  # lal
      - bc  # lal
      - libfftw3-dev  # lal
      - libframe-dev  # lalframe
      - gcc  # nds2
      - gfortran  # numpy/scipy
      - libblas-dev  # numpy/scipy
      - liblapack-dev  # numpy/scipy
      - libhdf5-serial-dev

python:
  - '2.7'
  - '3.5'

env:
  - PIP_FLAGS=""
  - PIP_FLAGS="--upgrade --pre"

matrix:
  allow_failures:
    - python: '3.5'
    - python: '2.7'
      env: PIP_FLAGS="--upgrade --pre"
  fast_finish: true

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install ${PIP_FLAGS} lalsuite
  - python -m pip install ${PIP_FLAGS} -r requirements.txt

install:
  # note: need --editable for executable coverage with `which ...` to work
  - python -m pip install --editable .

before_script:
  - python -m pip install ${PIP_FLAGS} coveralls "pytest>=2.8" pytest-runner unittest2

script:
  # run test suite
  - coverage run ./setup.py test
  # test executables
  - coverage run --append `which gw_summary` --help
  - coverage run --append `which gw_summary_pipe` --help
  - coverage run --append `which gwsumm-plot-triggers` --help
  - coverage run --append `which gwsumm-plot-guardian` --help

after_success:
  - coveralls

cache:
  apt: true
  pip: true
  directories:
    - lal-${LAL_VERSION}
    - lalframe-${LALFRAME_VERSION}
    - nds2-client-${NDS2_CLIENT_VERSION}
