language: python

python:
  - '2.7'
  - '3.5'

env:
  - PIP_FLAGS=""
  - PIP_FLAGS="--upgrade --pre"

matrix:
  allow_failures:
    - python: '3.5'
    - python: '2.7'
      env: PIP_FLAGS="--upgrade --pre"
  fast_finish: true

before_install:
  - python -m pip install --upgrade pip
  - python -m pip install ${PIP_FLAGS} -r requirements.txt

install:
  # note: need --editable for executable coverage with `which ...` to work
  - python -m pip install --editable .

before_script:
  - python -m pip install ${PIP_FLAGS} coveralls "pytest>=2.8" pytest-runner unittest2

script:
  # run test suite
  - coverage run ./setup.py test
  # test executables
  - coverage run --append `which gw_summary` --help
  - coverage run --append `which gw_summary_pipe` --help
  - coverage run --append `which gwsumm-plot-triggers` --help
  - coverage run --append `which gwsumm-plot-guardian` --help

after_success:
  - coveralls

cache:
  pip: true
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
